---
# tasks file for service-now-api
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "vars/default.yml"
  tags: always
- name: Include table-specific tasks when needed
  import_tasks: table_operations.yml

